---

- hosts: all
  name: My Web Group Apache Deployment
  become: yes
  vars: 
    doc_root: "/var/www/html"
    username: "Amit Vashist"
    doc_tomcat: "/opt/SP/apps"
    doc_tomcat_webapp: "/opt/SP/apps/tomcat/webapps/webapp"
 
  tasks: 
  - name: Install Apache2 Packages
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Install HTTPd Packages
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"
  
  - name: Bring up Apache Service 
    service: name=apache2 state=started

  - name: Deploy my custom Index Web page
    copy: src=files/index.html  dest={{doc_root}}/index.html

  - name: Deploy my custom Info Web page template
    template: src=templates/info.j2  dest={{doc_root}}/info.html

  - name: Tomcat Home Dir
    file: path={{doc_tomcat}}/tomcat state=directory

  - name: Install Default Java 1.8
    apt: name=default-jdk state=present

  - name: Download Tomcat Tarball
    get_url: url="http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz"  dest={{doc_tomcat}}/tomcat.tar.gz mode=0755

  - name: Extract Tomcat Tarball
    command: "tar zxf {{doc_tomcat}}/tomcat.tar.gz -C {{doc_tomcat}}/tomcat --strip-components 1"
  

  - name: Tomcat WebApp Dir
    file: path={{doc_tomcat_webapp}} state=directory
  
  - name: Deploy Jenkins Index Page
    copy: src=files/jenkins.html dest={{doc_tomcat_webapp}}/index.html
    notify: 
    - Restart Tomcat


  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start"


- hosts: all
  name: My Petclinic Deployment
  become: yes
  vars: 
    doc_tomcat: "/opt/SP/apps"
 
  tasks: 
  - name: Tomcat Home Dir
    file: path={{doc_tomcat}}/tomcat state=directory

  - name: Install Default Java 1.8
    apt: name=default-jdk state=present

  - name: Download Tomcat Tarball
    get_url: url="http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz"  dest={{doc_tomcat}}/tomcat.tar.gz mode=0755

  - name: Extract Tomcat Tarball
    command: "tar zxf {{doc_tomcat}}/tomcat.tar.gz -C {{doc_tomcat}}/tomcat --strip-components 1"
  
  - name: Deploy Jenkins Index Page
    copy: src=files/petclinic.war dest={{doc_tomcat}}/tomcat/webapps
    notify: 
    - Restart Tomcat


  handlers:
  - name: Restart Tomcat
    #shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh stop"
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start"
